version: '3.3'
services:
  primary_db:
    container_name: "primary_db"
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      TZ: 'Asia/Tokyo'
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    volumes:
      - primary-store:/var/lib/mysql
      - ./primary_db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./primary_db/sql:/docker-entrypoint-initdb.d
      - ./primary_db/DDL:/etc/ddl
      - ./logs/primary_db:/var/log/mysql

  secondary_db:
    container_name: "secondary_db"
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      TZ: 'Asia/Tokyo'
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    volumes:
      - secondary-store:/var/lib/mysql
      - ./secondary_db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./secondary_db/sql:/docker-entrypoint-initdb.d
      - ./secondary_db/DDL:/etc/ddl
      - ./logs/secondary_db:/var/log/mysql
 
volumes:
  primary-store:
  secondary-store:
